### ISSUE TITLE
Автотесты

### ISSUE THREAD

**Issue by Creatyclub** [Creaty-Co/creaty-api#172]
- [ ]  Создание новых страниц в соответствии со списком категорий / тегов
- [x] Формы (https://github.com/Creaty-Co/creaty-api/pull/317/commits/2b76b2b08aa107185ad087bc3f7f3f41d305cd6d)

**Comment by GentleEnvy** [comment]
> - [ ] Создание / удаление / изменение ментора
> - [ ] Проверить (дописать) создание / удаление / изменение категорий и тегов

Предлагаю выпилить этот функционал из API, т.к. теперь он в Django Admin

**Comment by GentleEnvy** [comment]
> Предлагаю выпилить этот функционал из API, т.к. теперь он в Django Admin

Пока оставлю, но тестировать не будем
