### ISSUE TITLE
Доработка функциональности админки Django

### ISSUE THREAD

**Issue by Creatyclub** [Creaty-Co/creaty-api#209]

**Comment by Creatyclub** [comment]
необходимо привести в соответствии функциональность админки Django с тем, что у нас было в админке на клиенте. 

Добавить: 
+ возможность привязывать 1 Тег (tag) в несколько разных категорий (category) одновременно
+ изменять Slug ментора
+ открывать из админки доступ к новым страницам менторов: параметр` draft: true / false`

**Comment by GentleEnvy** [comment]
> просматривать / изменять поле LinkedIn / portfolio link (должно принимать ссылки с ЛЮБОГО сайта, кроме вредоносных, разумеется)

Я не могу легко проверять ссылки на вредоносность. Придётся подключать какие-то сервисы, типа Google Safe Browsing, VirusTotal или Norton Safe Web.
