### ISSUE TITLE
Добавить доступы в админку через авторизацию для команды

### ISSUE THREAD

**Issue by Creatyclub** [Creaty-Co/creaty-api#212]

**Comment by GentleEnvy** [comment]
Тогда сначала зарегистрируй обе почты во всех средах

**Comment by Creatyclub** [comment]
@GentleEnvy  То есть на dev.creaty.club пока только верно? я же не могу пока нормально зарегаться на проде

**Comment by GentleEnvy** [comment]
ну да, пока на dev

**Comment by GentleEnvy** [comment]
дал доступы [creatyclub@gmail.com](https://dev-api.creaty.club/django_admin/users/user/9/change/), а [marina@creaty.club](mailto:marina@creaty.club) так и не увидел, но пока закрою issue
