### ISSUE TITLE
Доработать функциональность админки Django

### ISSUE THREAD

**Issue by Creatyclub** [Creaty-Co/creaty-api#224]
## Описание

Эта задача предполагает ряд обновлений в существующей системе, прежде всего, связанных с формами, *менторами*, тегами и категориями.

**1. Формы:**

Задача включает в себя создание функции, позволяющей просматривать все полученные заявки от пользователей. Предлагаемое решение - это универсальная таблица с возможностью фильтрации. Параметры для фильтрации должны включать:

- тип формы, из которой была получена заявка,
- тип запроса,
- статус регистрации и проверки пользователя.

Таблица должна отображать все соответствующие поля для каждого типа заявки, включая:

- имя,
- адрес электронной почты,
- информацию о том, как *ментор* может помочь,
- информацию о *менторе*,
- ссылку на профиль в LinkedIn или портфолио,
- время и дату получения заявки,
- ссылку на страницу, откуда была отправлена заявка.

2. **Менторы:**

В таблице "Менторы" требуется добавить дополнительные поля:

- электронная почта,
- страна/город/штат,
- компания/должность,
- ссылка на страницу *ментора*.

Кроме того, необходимо добавить функциональность для выбора одного или нескольких *менторов* и изменения параметра черновика. При добавлении нового *ментора* порядок полей должен быть реструктурирован для большей ясности, а также добавлены новые поля, такие как адрес электронной почты, языки и переключатель пробного встречи.

**3. Теги и категории:**

В таблице "Теги" требуется добавить следующие поля:

- категория(и), к которой относится тег,
- ссылка на страницу соответствующего тега.

Требуется создать дополнительную вкладку "Наставники внутри тега", где можно просмотреть таблицу *менторов*, связанных с определенным тегом. В таблице "Категории" должна быть добавлена ссылка на страницу соответствующей категории и вкладка "Наставники внутри категории".

**Comment by Creatyclub** [comment]
1. Необходимо добавить возможность просмотра всех полученных заявок от Юзеров
Полагаю, что лучше всего сделать 3 отдельных таблицы: 
— первая общими с заявками с сайта (то есть БЕЗ привязки к менторам) 
— вторая с заявками со страниц менторов
— с заявками на то, чтобы стать Ментором

Ну либо сделать общую таблицу, где заявки можно было бы фильтровать по следующим параметрам:
— по типу формы, откуда получена заявка (с привязкой к ментору / Без привязки / заявка от Ментора)
— по типу запроса (применимо к заякам с Привязкой к менторам: Free trial session / 1 session / Session Pack) 
— юзер зарегистрирован / не зарегистрирован (применимо ко всем заявкам, кроме заявки на Ментора) 
— юзер верифицирован / не верифицирован 
— 

![Image](https://github.com/Creaty-Co/creaty-api/assets/98054391/dc1d2385-0840-44c3-ae0d-091362badca0)

2.

**Comment by Creatyclub** [comment]
2. Mentors 
**Таблица менторов**
необходимо добавить поля: 
— email
— country / city / state
— company / title 
— ссылку на страницу ментора 🟢(чтобы можно было бы кликнуть и она открывалась бы в новой влкадке)
Если можно, чтобы Avatar был бы показан именно как картинка, было бы просто супер

функционально необходимо добавить возможность: 
Выбирать одного / несколько менторов и менять параметр `draft: true / false`


**Добавление нового ментора**
Необходимо сменить порядок полей, потому как сейчас всё в разнобой — сложно понять что к чему. Порядок должен быть такой (с учётом полей, которые нужно **Добавить**): 
1. Тоггл `draft: false / true`
2. Slug
3. LinkedIn profile / portfolio Link
4. Avatar (если можно, чтобы показывалась бы картинка, было бы просто супер) 
5. Resume
6. Name
7. Last name
8. email address (добавить 🟢)
9. Country 
10. City, State
11. Languages (добавить 🟢)
12. Tag set (я не понял как добавлять теги новому ментору😅)
13. Experience 
14. What help (переименовать на How can I help)
15. Price 
16. Trial meeting (должен быть тоггл true / false 🟢)
17. Package (нужно объединить с основной вкладкой 🟢)

**Comment by Creatyclub** [comment]
### 3. Tags & Categories
![Image](https://github.com/Creaty-Co/creaty-api/assets/98054391/48ad2843-81ae-44dd-b329-1ab6cb14415a)

**Теги**
в таблице Тегов необходимо добавить поля: 
— к какой категории(ям) относится тег
— ссылку на страницу соответствующего тега (при клике переход на страницу в новой вкладке браузера)

Также нужно сделать дополнительную вкладку **Mentors inside tag**, где можно было бы просматривать таблицу менторов, которые относятся к конкретному тегу
(со всеми полями, описанными выше для данной таблицы)
![Image](https://github.com/Creaty-Co/creaty-api/assets/98054391/0a01f17c-e82f-4534-bb9a-c990570a0943)


**Категории**
В таблице Категорий нужно добавить поля: 
— ссылку на страницу соответствующей Категории (при клике переход) 

Также нужно сделать аналогичную вкладку Mentors inside category, внутри страницы категории

**Comment by GentleEnvy** [comment]
> 1. Forms
>> Полагаю, что лучше всего сделать 3 отдельных таблицы:

Это вряд ли возможно, проще сделать через фильтр

>> Либо сделать общую таблицу, где заявки можно было бы фильтровать по следующим параметрам:
>>> - по типу формы, откуда получена заявка (с привязкой к ментору / Без привязки / заявка от Ментора)

Сейчас есть типы:
- become_mentor— Станьте ментором
- choose_mentor — Получить помощь в подборе ментора
- test_meeting — Бесплатная тестовая встреча
- still_questions — Ещё остались вопросы
- signup_mentor — Записаться к ментору

Сделаю фильтрацию по этим значениям.

>>> - по типу запроса (применимо к заякам с Привязкой к менторам: Free trial session / 1 session / Session Pack)

Для этого нужно сначала выполнить #211

>>> - юзер зарегистрирован / не зарегистрирован (применимо ко всем заявкам, кроме заявки на Ментора)

В заявке на ментора это поле всё равно будет (скорее всего всегда как "не зарегистрирован"), потому что тяжело убрать конкретное поле, которое есть у модели

> 2. Mentors
>> Таблица менторов
>>> Если можно, чтобы Avatar был бы показан именно как картинка, было бы просто супер

Попробую, вроде это возможно

>> Добавление нового ментора
>>> 3. LinkedIn profile / portfolio Link

Сейчас у ментора вообще нет такого поля. Могу добавить, тогда сделаю его без проверок - т.е. просто любая ссылка ?

>>> 8. email address (добавить 🟢)

Такого поля тоже нет, оно есть только у User. Добавить привязку User к Mentor ? Это лучше отдельно обсудить

>>> 12. Tag set (я не понял как добавлять теги новому ментору😅)

Изменю на "Tags". Чтобы добавить, зажать CTRL (Command на маке) и тыкнуть на тег из списка. Могу потом показать

>>> 17. Package (нужно объединить с основной вкладкой 🟢)

Вообще это настраиваемся штука в ADMIN INTERFACE -> [Themes](https://dev-api.creaty.club/django_admin/admin_interface/theme/)
Можешь сам поиграться с темой админки

**Comment by Creatyclub** [comment]
> Добавление нового ментора

> > LinkedIn profile / portfolio Link

> > > Сейчас у ментора вообще нет такого поля. Могу добавить, тогда сделаю его без проверок - т.е. просто любая ссылка ?

Да, давай добавим + опять же для Димы получается нужно будет, наверное, доработать end point для формы become_mentor 



> > > email address (добавить 🟢)

> Такого поля тоже нет, оно есть только у User. Добавить привязку User к Mentor ? Это лучше отдельно обсудить

Ну мы по идее должны получать эти данные вместе с заявкой become_mentor — но давай обсудим, да. Может мог бы описать, какие именно вопросы тебя заботят в связи с этим пунктом?
