### ISSUE TITLE
Вытащить в админку Django оставшиеся модели (функционал)

### ISSUE THREAD

**Issue by Creatyclub** [Creaty-Co/creaty-api#356]
- [x] 1. Добавить секцию в меню админки **Website Links**, где внутри сделать 2 подраздела: **Messenger Links** и **Footer Links** с соответствующим функционалом
(Для подраздела **Messenger Links** необходимо вытащить (иди добавить) возможность также загружать в качестве иконок картинки формата SVG)

- [x] 2. Добавить секцию в меню админки **FAQ** с соответствующим функционалом 
(вопрос и ответ, разумеется должны быть на одной странице, иначе будет крайне сложно редактировать)

**Comment by GentleEnvy** [comment]
Из особенностей Django Admin, получилось добавить всё только в секцию `PAGES`, которую переименовал в `PAGES + LINKS`
