### ISSUE TITLE
Оценить затраты на Kubernetes

### ISSUE THREAD

**Issue by Creatyclub** [Creaty-Co/creaty-api#444]

**Comment by GentleEnvy** [comment]
12$ - публичный IP (он всегда нужен, но всегда только один)
Каждый Гб оперативной памяти стоит 6$. На 3 среды требуется 6-8 Гб => +36-48 $
Диск стоит мало, на него потребуется ещё +2$

Итого: 50-62 $
Примечание: текущие затраты на 2 ВМ (под dev+stage и prod) - 18 + 21 $ = 39$
