### ISSUE TITLE
Сделать часть полей НЕ обязательными для заполнения при создании ментора

### ISSUE THREAD

**Issue by Creatyclub** [Creaty-Co/creaty-api#79]
В итоге должен быть вот такой список полей, обязательные отмечены:

1. Имя — first_name* (🔴 обязательное)
2. Фамилия — last_name* (🔴 обязательное)
3. Профессия — profession* (🔴 обязательное)
4. Компания — company (🟢 НЕ обязательное)
5. Оплата — price* (🔴 обязательное)
6. Валюта — price_currency* — УДАЛИТЬ, валюта всегда доллары $
7. Тег — tag_set*  (🔴 обязательно выбрать хотя бы 1 тег)
8. Местоположение
    страна — country* (🔴 обязательное)
    Город — city (🟢 НЕ обязательное)
    Город на русском — УДАЛИТЬ
9. Язык — language*  (🔴 обязательно выбрать хотя бы 1 язык, по умолчанию должен стоять Английский) 
10. Аватарка — avatar  (🟢 НЕ обязательное)
11. Портфолио — portfolio — УДАЛИТЬ 
12. Опыт — experience (🟢 НЕ обязательное)
13. С чем помогу — help_with (🟢 НЕ обязательное)
14. Резюме — top_info* (сейчас это, наверное, просто info*) (🔴 обязательное)
15. Пакеты — packages (🟢 НЕ обязательное)
16. 15 минут бесплатной встречи — пока оставляем тоггл, однако потом скорее всего тоже удалим

В дополнение скажу, что если это довольно быстро и просто, то для меньшей путаницы предлагаю поля в самой Админке называть также, как и они будут называться в коде. 

ВСЕ необязательные поля, в случае отсутствия value, в идеале передают null, но НЕ ломают верстку 😌

![Image](https://user-images.githubusercontent.com/98054391/213541450-4a606d1d-99dc-49a3-9cf6-727a1071de97.png)

**Comment by GentleEnvy** [comment]
Предлагаю оставить price_currency, но пока что сделать на фронте выбор из 1 варианта - доллара.
Просто если потом мы захотим предоставить возможность расплачиваться в разной валюте, зачем это убирать полностью?

**Comment by Creatyclub** [comment]
Ок, давай тогда так и сделаем. Макса @mapcic — это кажется, тоже тебе
