### ISSUE TITLE
Авторизация по JWT

### ISSUE THREAD

**Issue by GentleEnvy** [Creaty-Co/creaty-api#84]
## Описание

Endpoints:
(напишет @mapcic)

## Тест кейсы

- [x] юзер существует, валидный email - 200
- [x] юзер не существует - 401
- [x] юзер существует, неверный пароль - 401

**Comment by mapcic** [comment]
POST /login - Route for user authentication, returns a JWT token and refresh token.
POST /refresh - Route to refresh a JWT token with a refresh token.
GET /protected - Route that requires a JWT token for access, returns a protected resource.
DELETE /logout - Route to delete the refresh token, effectively logging out the user.
